[versions]
agp = "8.8.0"
kotlin = "2.1.10"

[libraries]
appcompat = "androidx.appcompat:appcompat:1.7.0"
core-ktx = "androidx.core:core-ktx:1.15.0"
pdfium-android = "com.github.smontesdeoca23:PdfiumAndroid:2.0.3"

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
